// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CopyText(arg1:string):Promise<void>;

export function EnvStatus():Promise<main.EnvStatus>;

export function IsZcodeRunning():Promise<main.ProcStatus>;

export function KillZcode():Promise<main.OpResult>;

export function ListDefaultTasks():Promise<Array<main.TaskItem>>;

export function ListProjectFiles(arg1:string):Promise<Array<main.FileItem>>;

export function ListProjectTasks(arg1:string):Promise<main.ProjectTasksResult>;

export function MigratePaths(arg1:string,arg2:string):Promise<main.MigrateResult>;

export function NowStamp():Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function RemoveProject(arg1:string):Promise<main.RemoveProjectResult>;

export function RemoveTask(arg1:string):Promise<main.RemoveTaskResult>;

export function ScanPaths():Promise<main.ScanResult>;

export function WbHome():Promise<Record<string, any>>;

export function WbKill():Promise<main.OpResult>;

export function WbMigrate(arg1:string,arg2:string):Promise<main.WbMigrateResult>;

export function WbPreview(arg1:string,arg2:string):Promise<main.WbMigrateResult>;

export function WbRunning():Promise<boolean>;

export function WbScan():Promise<main.WbBroken>;

export function WbSessionFiles(arg1:string):Promise<Array<main.WbFileItem>>;

export function WbSessions():Promise<Array<main.WbSession>>;

export function WbSpaceFiles(arg1:string):Promise<Array<main.WbFileItem>>;

export function WbSpaceRemove(arg1:string):Promise<main.WbRemoveResult>;

export function WbSpaceRemoveBatch(arg1:Array<string>):Promise<main.WbRemoveResult>;

export function WbSpaceTasks(arg1:string):Promise<main.SpaceTasksResult>;

export function WbSpaces():Promise<Array<main.SpaceItem>>;

export function WbTaskRemove(arg1:string):Promise<main.WbRemoveResult>;

export function WbUid():Promise<string>;
