// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function EnvStatus() {
  return window['go']['main']['App']['EnvStatus']();
}

export function IsZcodeRunning() {
  return window['go']['main']['App']['IsZcodeRunning']();
}

export function KillZcode() {
  return window['go']['main']['App']['KillZcode']();
}

export function ListDefaultTasks() {
  return window['go']['main']['App']['ListDefaultTasks']();
}

export function ListProjectFiles(arg1) {
  return window['go']['main']['App']['ListProjectFiles'](arg1);
}

export function ListProjectTasks(arg1) {
  return window['go']['main']['App']['ListProjectTasks'](arg1);
}

export function MigratePaths(arg1, arg2) {
  return window['go']['main']['App']['MigratePaths'](arg1, arg2);
}

export function NowStamp() {
  return window['go']['main']['App']['NowStamp']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function ScanPaths() {
  return window['go']['main']['App']['ScanPaths']();
}

export function WbHome() {
  return window['go']['main']['App']['WbHome']();
}

export function WbKill() {
  return window['go']['main']['App']['WbKill']();
}

export function WbMigrate(arg1, arg2) {
  return window['go']['main']['App']['WbMigrate'](arg1, arg2);
}

export function WbPreview(arg1, arg2) {
  return window['go']['main']['App']['WbPreview'](arg1, arg2);
}

export function WbRunning() {
  return window['go']['main']['App']['WbRunning']();
}

export function WbScan() {
  return window['go']['main']['App']['WbScan']();
}

export function WbSessionFiles(arg1) {
  return window['go']['main']['App']['WbSessionFiles'](arg1);
}

export function WbSessions() {
  return window['go']['main']['App']['WbSessions']();
}

export function WbSpaceFiles(arg1) {
  return window['go']['main']['App']['WbSpaceFiles'](arg1);
}

export function WbSpaceRemove(arg1) {
  return window['go']['main']['App']['WbSpaceRemove'](arg1);
}

export function WbSpaceRemoveBatch(arg1) {
  return window['go']['main']['App']['WbSpaceRemoveBatch'](arg1);
}

export function WbSpaceTasks(arg1) {
  return window['go']['main']['App']['WbSpaceTasks'](arg1);
}

export function WbSpaces() {
  return window['go']['main']['App']['WbSpaces']();
}

export function WbTaskRemove(arg1) {
  return window['go']['main']['App']['WbTaskRemove'](arg1);
}

export function WbUid() {
  return window['go']['main']['App']['WbUid']();
}
